name: Deploy Static Website to S3

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # Change to your AWS region

      # Step 3: Sync HTML/CSS files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://amansdlc.com \
            --delete \
            --exact-timestamps

